export enum ItemStats {
    ATK = "ATK",
    CRITRATE = "CRITRATE",
    CRITDMG = "CRITDMG",
    PYRODPS = "PYRODPS",
    HYDRODPS = "HYDRODPS",
    ELECTRODPS = "ELECTRODPS",
    CRYODPS = "CRYODPS",
    ANEMODPS = "ANEMODPS",
    GEODPS = "GEODPS",
    DENDRODPS = "DENDRODPS"
}